src/Northwind.MusicStore.WebUI/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Northwind.MusicStore.RepositoryInterfaces;
using Northwind.MusicStore.WebUI.Models;
using Northwind.MusicStore.WebUI.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ICartRepository _carts;
        private readonly IAlbumsRepository _albums;
        private readonly ShoppingCartFactory _shoppingCartFactory;
        //MusicStoreEntities storeDB = new MusicStoreEntities();

        public ShoppingCartController(ICartRepository carts, IAlbumsRepository albums, ShoppingCartFactory shoppingCartFactory)
        {
            _carts = carts;
            _albums = albums;
            _shoppingCartFactory = shoppingCartFactory;
        }

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = _shoppingCartFactory.GetCart(this.HttpContext);

            // Configure our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            //var addedAlbum = storeDB.Albums
            //    .Single(album => album.AlbumId == id);
            var addedAlbum = _albums.Get(album => album.AlbumId == id).Single();

            // Add it to the shopping cart
            var cart = _shoppingCartFactory.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = _shoppingCartFactory.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            //string albumName = storeDB.Carts.Single(item => item.RecordId == id).Album.Title;
            string albumName = _carts.Get().Include(c=>c.Album).Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = _shoppingCartFactory.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }

}

src/Northwind.MusicStore.WebUI/Controllers/StoreController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Northwind.MusicStore.WebUI.Filters;
using Northwind.MusicStore.RepositoryInterfaces;
using Northwind.MusicStore.BusinessInterfaces;

namespace Northwind.MusicStore.WebUI.Controllers
{

    [LogAction]
    public class StoreController : Controller
    {
        private readonly IGenreRepository _genres;
        private readonly IAlbumsRepository _albums;
        private readonly ILogProvider _log;
        //private readonly ILog _log;

        public StoreController(IGenreRepository genres, IAlbumsRepository albums, ILogProvider log)
        {
            _genres = genres;
            _albums = albums;
            _log = log;
            //_log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        }
        
        public ActionResult Index()
        {
            Session["HitIndex"] = (int)(Session["HitIndex"] ?? 0) + 1;
            _log.ErrorFormat("The StoreController.Index action has been hit {0} times this session", Session["HitIndex"]);
            
            var genres = _genres.Get().ToList();
            return View(genres);
        }
        
        // GET: /Store/Browse?genre=Disco
        //[LogAction]
        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            //var genreModel = storeDB.Genres.Include("Albums")
            //  .Single(g => g.Name == genre);
            var genreModel = _genres.Get()
                .Include(a=>a.Albums)
                .Single(g => g.Name == genre);

            return View(genreModel);
        }
        //
        // GET: /Store/Details/5
        public ActionResult Details(int id)
        {
            //var album = storeDB.Albums.Find(id);
            var album = _albums.Get(a=>a.AlbumId==id)
                .Include(a=>a.Genre)
                .Include(a => a.Artist)
                .SingleOrDefault();

            return View(album);
        }

        //
        // GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = _genres.Get().ToList();
            return PartialView(genres);
        }

    }
}

src/Northwind.MusicStore.WebUI/Views/Store/Browse.cshtml
@model Northwind.MusicStore.Domain.Genre
 
@{
    ViewBag.Title = "Browse Albums";
}
 
<div class="genre">
    <h3><em>@Model.Name</em> Albums</h3>
 
    <ul id="album-list">
        @foreach (var album in Model.Albums)
        {
            <li>
                <a href="@Url.Action("Details", 
                    new { id = album.AlbumId })">
                    <img alt="@album.Title" 
                        src="@album.AlbumArtUrl" />
                    <span>@album.Title</span>
                </a>
            </li>
        }
    </ul>
</div>

src/Northwind.MusicStore.WebUI/Views/Store/Details.cshtml
@model Northwind.MusicStore.Domain.Album
@{
    ViewBag.Title = "Album - " + Model.Title;
 }
<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title"
src="@Model.AlbumArtUrl" />
</p>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Artist:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}",
Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", 
        "ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
</div>

src/Northwind.MusicStore.WebUI/Views/Store/GenreMenu.cshtml
@model IEnumerable<Northwind.MusicStore.Domain.Genre>
<ul id="categories">
    @foreach (var genre in Model)
    {
        <li>@Html.ActionLink(genre.Name,"Browse", "Store", new { Genre = genre.Name }, null)</li>
    }
</ul>

src/Northwind.MusicStore.WebUI/Views/Store/Index.cshtml
@model IEnumerable<Northwind.MusicStore.Domain.Genre>
@{
    ViewBag.Title = "Store";
}
<h3>Browse Genres</h3>
    <p>
        Select from @Model.Count()
        genres:
    </p>
    <ul>
        @foreach (var genre in Model)
        {
            <li>@Html.ActionLink(genre.Name, "Browse", new { genre = genre.Name })</li>
        }
    </ul>